//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;


    public partial class os
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public os()
        {
            this.osxservico = new HashSet<osxservico>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<System.DateTime> DataContratacao { get; set; }
        public Nullable<System.DateTime> DataExecucao { get; set; }
        
        [JsonIgnore]
        public virtual cliente cliente { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<osxservico> osxservico { get; set; }
    }
}
