//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;


    public partial class osxservico
    {
        public int Id { get; set; }
        public Nullable<int> IdOs { get; set; }
        public Nullable<int> IdServico { get; set; }
    
        [JsonIgnore]
        public virtual os os { get; set; }
        [JsonIgnore]
        public virtual servicos servicos { get; set; }
    }
}
